# Numpy


In [39]:
import numpy as np

In [40]:
print("Hello Worls")

Hello Worls


In [41]:
myarr=np.array([[1,2,3,4,5]],np.int8) # create array ..
print(myarr)

[[1 2 3 4 5]]


In [42]:
myarr

array([[1, 2, 3, 4, 5]], dtype=int8)

In [43]:
myarr[0,1]

np.int8(2)

In [44]:
myarr.shape

(1, 5)

In [45]:
myarr.dtype

dtype('int8')

In [46]:
myarr[0,1]=20

In [47]:
myarr # Now 2 changed to 20 ..

array([[ 1, 20,  3,  4,  5]], dtype=int8)

# Array Conversion : Conversion from other python Structures

In [48]:
listarray = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [49]:
listarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
listarray.dtype

dtype('int64')

In [51]:
listarray.shape

(2, 5)

In [52]:
listarray.size

10

In [53]:
zeros=np.zeros((3,4))

In [54]:
zeros # give a 3 , 4 matrix of zeros ..

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
rng = np.arange(15) # create array from 0 to 14

In [56]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
lspace = np.linspace(1,5,10) # create 10 values between 1 to 5

In [58]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
emp = np.empty((4,6)) # create empty array of given shape

In [60]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.69118787e-306],
       [1.20161526e-306, 6.23059726e-307, 2.22522597e-306,
        1.06810268e-306, 6.23052935e-307, 1.60221072e-306],
       [6.89806849e-307, 1.42419530e-306, 8.45559303e-307,
        1.06811422e-306, 1.05694828e-307, 1.42410974e-306]])

In [61]:
arr= np.arange(99) # create array from 0 to 98

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
arr.reshape(3,33) # reshape array to 3 rows and 33 columns


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [64]:
arr=arr.ravel()

In [65]:
arr.shape

(99,)

# AXIS 

#AXIS 0 -- > COLUMN

#AXIS 1 -- > ROW

In [66]:
x = [[1,2 ,3],[4,5,6],[7,8,9]]

In [67]:
arr=np.array(x)

In [68]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr.sum(axis=0) # sum of each column

array([12, 15, 18])

In [70]:
arr.sum(axis = 1) # sum of each row

array([ 6, 15, 24])

In [ ]:
arr.T # transpose of array .. # rows become columns and columns become rows

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
arr.flat

In [73]:
arr.size

9

In [74]:
one = np.array([1,3,56,6,7])

In [76]:
one.argmax() # index of maximum value

np.int64(2)

In [77]:
one.argmin() # index of minimum value

np.int64(0)

In [78]:
one.argsort() # indices that would sort the array

array([0, 1, 3, 4, 2])